### PR TITLE
Made /usr/bin scripts executable. Fixed permissions check on server.key

### PR DESCRIPTION
**Pull request by themicster**
Removed presumably unused and not needed check in the /usr/bin scripts for PG_SSL when it was on it would break things. The permissions postgres wants for server.key is 0600, so changed the check in functions. I only did this for postgres 13 since that's what I'm using right now, so I didn't check the others.

### CODE REVIEW

**Comment by gjrtimmer** [comment]
LGTM, the other versions are built automatically, and all of them use the same rootfs.

Thank you so much for your contribution.

**Comment by gjrtimmer** [comment]
@themicster please note that today, I actually renamed the master branch to `main`

Also this weekend, I will try on incorporating auto-failover, node election etc, which can be configured through environment variables.

**Comment by gjrtimmer** [comment]
I forgot to mention, I use conventional commits in this repository, so I rebased and changed your initial commit message, I will also try to write a contribution manual. Very grateful for your contribution. Have you tried to automatic upgrade? For me it has been working amazing for a long time. I would appreciate some feedback on it.

**Comment by themicster** [comment]
I have not tried auto upgrade. How is that done, just stop the container and start a newer version? I would have to do the same on my primary servers which are using Kubegres and I'm not sure they support that upgrade process. If I get a chance to try this I'll let you know. It's great to see a new docker postgres in the style of sameersbn as he is no longer maintaining his postgresql project it seems.

**Comment by gjrtimmer** [comment]
@themicster, Missed the notification, so the upgrade progress is pretty cool with this one, you stop the container and start a new version with the same data directory, now I do not know what version you are on right now. But to be safe, you first stop it, then start the same version over it. It should create some hidden directories with the current postgres version, etc, this is needed for the upgrade. Then just start a new version over it. You can try it out locally.

**Pull request merged**
